# Welcome to Jekyll!title: AI+HEP in East Asia
email: contact@ai-hep.org
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#   - vmikuni@cern.ch - huilin.qu@cern.ch
title: AI+HEP in East Asia
email: tianjiresearch@gmail.com, vmikuni@cern.ch, huilin.qu@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  A collaborative community of high energy physicists in East Asia and beyond exploring 
  the intersection of artificial intelligence and particle physics. We organize 
  workshops, seminars, and educational activities to advance AI+HEP research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ai-hep.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: ai-hep

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima theme settings
minima:
  skin: auto
  # social_links:
    # github: ai-hep
    # twitter: your_username
    # linkedin: your_username

# Header navigation
header_pages:
  - 00-about.markdown
  - 01-organizers.markdown
  - 02-workshops.markdown
  - 03-seminars.markdown
  - 04-journalclubs.markdown
  - 05-curriculum.markdown
  - 06-projectboard.markdown

# Custom variables
organization: "AI+HEP East Asia Community"
tagline: "Advancing AI in High Energy Physics"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
